[package]
name = "asyncomplete-fuzzy-matcher"
version = "0.1.0"
authors = ["tsufeki <tsufeki@ymail.com>"]
edition = "2018"

[dependencies]
fuzzy-matcher = "0.3.4"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
